/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getLength <em>Length</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getScore <em>Score</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getTime <em>Time</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getAmount <em>Amount</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getWeapon <em>Weapon</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getDefault()
 * @model
 * @generated
 */
public interface Default extends EObject
{
  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getDefault_Length()
   * @model
   * @generated
   */
  String getLength();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(String value);

  /**
   * Returns the value of the '<em><b>Score</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Score</em>' attribute.
   * @see #setScore(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getDefault_Score()
   * @model
   * @generated
   */
  String getScore();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getScore <em>Score</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Score</em>' attribute.
   * @see #getScore()
   * @generated
   */
  void setScore(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getDefault_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getDefault_Amount()
   * @model
   * @generated
   */
  String getAmount();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(String value);

  /**
   * Returns the value of the '<em><b>Weapon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weapon</em>' attribute.
   * @see #setWeapon(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getDefault_Weapon()
   * @model
   * @generated
   */
  String getWeapon();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Default#getWeapon <em>Weapon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weapon</em>' attribute.
   * @see #getWeapon()
   * @generated
   */
  void setWeapon(String value);

} // Default
