/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Food Init Display</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getFoodIcon <em>Food Icon</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getIconsize <em>Iconsize</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getFoodKind <em>Food Kind</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getProduce <em>Produce</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getFoodTag <em>Food Tag</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodInitDisplay()
 * @model
 * @generated
 */
public interface FoodInitDisplay extends EObject
{
  /**
   * Returns the value of the '<em><b>Food Icon</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.group16.greedySnake.IconTag}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Food Icon</em>' containment reference list.
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodInitDisplay_FoodIcon()
   * @model containment="true"
   * @generated
   */
  EList<IconTag> getFoodIcon();

  /**
   * Returns the value of the '<em><b>Iconsize</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iconsize</em>' attribute.
   * @see #setIconsize(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodInitDisplay_Iconsize()
   * @model
   * @generated
   */
  String getIconsize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getIconsize <em>Iconsize</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iconsize</em>' attribute.
   * @see #getIconsize()
   * @generated
   */
  void setIconsize(String value);

  /**
   * Returns the value of the '<em><b>Food Kind</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.group16.greedySnake.FoodKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Food Kind</em>' containment reference list.
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodInitDisplay_FoodKind()
   * @model containment="true"
   * @generated
   */
  EList<FoodKind> getFoodKind();

  /**
   * Returns the value of the '<em><b>Produce</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Produce</em>' containment reference.
   * @see #setProduce(RandomFoodSize)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodInitDisplay_Produce()
   * @model containment="true"
   * @generated
   */
  RandomFoodSize getProduce();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getProduce <em>Produce</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Produce</em>' containment reference.
   * @see #getProduce()
   * @generated
   */
  void setProduce(RandomFoodSize value);

  /**
   * Returns the value of the '<em><b>Food Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Food Tag</em>' attribute.
   * @see #setFoodTag(int)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodInitDisplay_FoodTag()
   * @model
   * @generated
   */
  int getFoodTag();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay#getFoodTag <em>Food Tag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Food Tag</em>' attribute.
   * @see #getFoodTag()
   * @generated
   */
  void setFoodTag(int value);

} // FoodInitDisplay
