/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Food Members</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodMembers#getFood <em>Food</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodMembers()
 * @model
 * @generated
 */
public interface FoodMembers extends EObject
{
  /**
   * Returns the value of the '<em><b>Food</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Food</em>' containment reference.
   * @see #setFood(FoodInitDisplay)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodMembers_Food()
   * @model containment="true"
   * @generated
   */
  FoodInitDisplay getFood();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.FoodMembers#getFood <em>Food</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Food</em>' containment reference.
   * @see #getFood()
   * @generated
   */
  void setFood(FoodInitDisplay value);

} // FoodMembers
