/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Food Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.FoodTime#getFoodTime <em>Food Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodTime()
 * @model
 * @generated
 */
public interface FoodTime extends TimeLimited
{
  /**
   * Returns the value of the '<em><b>Food Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Food Time</em>' attribute.
   * @see #setFoodTime(int)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getFoodTime_FoodTime()
   * @model
   * @generated
   */
  int getFoodTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.FoodTime#getFoodTime <em>Food Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Food Time</em>' attribute.
   * @see #getFoodTime()
   * @generated
   */
  void setFoodTime(int value);

} // FoodTime
