/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial Speed Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.InitialSpeedSpecification#getSpeedGroup <em>Speed Group</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getInitialSpeedSpecification()
 * @model
 * @generated
 */
public interface InitialSpeedSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Speed Group</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl2.group16.greedySnake.SpeedGroup}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed Group</em>' containment reference list.
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getInitialSpeedSpecification_SpeedGroup()
   * @model containment="true"
   * @generated
   */
  EList<SpeedGroup> getSpeedGroup();

} // InitialSpeedSpecification
