/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Maxsize</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Maxsize#getMinsize <em>Minsize</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMaxsize()
 * @model
 * @generated
 */
public interface Maxsize extends EObject
{
  /**
   * Returns the value of the '<em><b>Minsize</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minsize</em>' attribute.
   * @see #setMinsize(int)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMaxsize_Minsize()
   * @model
   * @generated
   */
  int getMinsize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Maxsize#getMinsize <em>Minsize</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minsize</em>' attribute.
   * @see #getMinsize()
   * @generated
   */
  void setMinsize(int value);

} // Maxsize
