/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Minsize</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Minsize#getMaxsize <em>Maxsize</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMinsize()
 * @model
 * @generated
 */
public interface Minsize extends EObject
{
  /**
   * Returns the value of the '<em><b>Maxsize</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maxsize</em>' attribute.
   * @see #setMaxsize(int)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMinsize_Maxsize()
   * @model
   * @generated
   */
  int getMaxsize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Minsize#getMaxsize <em>Maxsize</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maxsize</em>' attribute.
   * @see #getMaxsize()
   * @generated
   */
  void setMaxsize(int value);

} // Minsize
