/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getDir <em>Dir</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getCoor <em>Coor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getMoveVal <em>Move Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMove()
 * @model
 * @generated
 */
public interface Move extends EObject
{
  /**
   * Returns the value of the '<em><b>Dir</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dir</em>' reference.
   * @see #setDir(dis)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMove_Dir()
   * @model
   * @generated
   */
  dis getDir();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getDir <em>Dir</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dir</em>' reference.
   * @see #getDir()
   * @generated
   */
  void setDir(dis value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMove_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Coor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coor</em>' attribute.
   * @see #setCoor(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMove_Coor()
   * @model
   * @generated
   */
  String getCoor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getCoor <em>Coor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coor</em>' attribute.
   * @see #getCoor()
   * @generated
   */
  void setCoor(String value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMove_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Move Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move Val</em>' attribute.
   * @see #setMoveVal(int)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getMove_MoveVal()
   * @model
   * @generated
   */
  int getMoveVal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.Move#getMoveVal <em>Move Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move Val</em>' attribute.
   * @see #getMoveVal()
   * @generated
   */
  void setMoveVal(int value);

} // Move
