/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obstacle Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.ObstacleTime#getObstacleTime <em>Obstacle Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getObstacleTime()
 * @model
 * @generated
 */
public interface ObstacleTime extends TimeLimited
{
  /**
   * Returns the value of the '<em><b>Obstacle Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obstacle Time</em>' attribute.
   * @see #setObstacleTime(int)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getObstacleTime_ObstacleTime()
   * @model
   * @generated
   */
  int getObstacleTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.ObstacleTime#getObstacleTime <em>Obstacle Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obstacle Time</em>' attribute.
   * @see #getObstacleTime()
   * @generated
   */
  void setObstacleTime(int value);

} // ObstacleTime
