/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getOptionSpecification()
 * @model
 * @generated
 */
public interface OptionSpecification extends EObject
{
} // OptionSpecification
