/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getParamSpec()
 * @model
 * @generated
 */
public interface ParamSpec extends VarSpec
{
} // ParamSpec
