/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Field Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.StartFieldDeclaration#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getStartFieldDeclaration()
 * @model
 * @generated
 */
public interface StartFieldDeclaration extends OptionSpecification
{
  /**
   * Returns the value of the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' reference.
   * @see #setField(GlobalFieldInitialisation)
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#getStartFieldDeclaration_Field()
   * @model
   * @generated
   */
  GlobalFieldInitialisation getField();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.group16.greedySnake.StartFieldDeclaration#getField <em>Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' reference.
   * @see #getField()
   * @generated
   */
  void setField(GlobalFieldInitialisation value);

} // StartFieldDeclaration
