/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class GreedySnakeDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
