/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class GreedySnakeLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public GreedySnakeLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
