/*
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GreedySnakeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/mydsl2/group16/parser/antlr/internal/InternalGreedySnake.tokens");
	}
}
