/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GreedySnakeRuntimeModule extends AbstractGreedySnakeRuntimeModule {
}
