/*
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGreedySnakeValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage.eINSTANCE);
		return result;
	}
}
