/*
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GreedySnakeStandaloneSetup extends GreedySnakeStandaloneSetupGenerated {

	def static void doSetup() {
		new GreedySnakeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
