/*
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGreedySnakeScopeProvider extends DelegatingScopeProvider {
}
