/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl2.group16.greedySnake.AllItemVarSpec;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>All Item Var Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AllItemVarSpecImpl extends VarSpecImpl implements AllItemVarSpec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllItemVarSpecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreedySnakePackage.Literals.ALL_ITEM_VAR_SPEC;
  }

} //AllItemVarSpecImpl
