/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl2.group16.greedySnake.BackgroundIcon;
import org.xtext.example.mydsl2.group16.greedySnake.BackgroundTag;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Background Icon</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.BackgroundIconImpl#getBackgroundTag <em>Background Tag</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BackgroundIconImpl extends MinimalEObjectImpl.Container implements BackgroundIcon
{
  /**
   * The cached value of the '{@link #getBackgroundTag() <em>Background Tag</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBackgroundTag()
   * @generated
   * @ordered
   */
  protected EList<BackgroundTag> backgroundTag;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BackgroundIconImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreedySnakePackage.Literals.BACKGROUND_ICON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BackgroundTag> getBackgroundTag()
  {
    if (backgroundTag == null)
    {
      backgroundTag = new EObjectContainmentEList<BackgroundTag>(BackgroundTag.class, this, GreedySnakePackage.BACKGROUND_ICON__BACKGROUND_TAG);
    }
    return backgroundTag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreedySnakePackage.BACKGROUND_ICON__BACKGROUND_TAG:
        return ((InternalEList<?>)getBackgroundTag()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreedySnakePackage.BACKGROUND_ICON__BACKGROUND_TAG:
        return getBackgroundTag();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreedySnakePackage.BACKGROUND_ICON__BACKGROUND_TAG:
        getBackgroundTag().clear();
        getBackgroundTag().addAll((Collection<? extends BackgroundTag>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.BACKGROUND_ICON__BACKGROUND_TAG:
        getBackgroundTag().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.BACKGROUND_ICON__BACKGROUND_TAG:
        return backgroundTag != null && !backgroundTag.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //BackgroundIconImpl
