/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.FoodMembers;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Food Members</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.FoodMembersImpl#getFood <em>Food</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FoodMembersImpl extends MinimalEObjectImpl.Container implements FoodMembers
{
  /**
   * The cached value of the '{@link #getFood() <em>Food</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFood()
   * @generated
   * @ordered
   */
  protected FoodInitDisplay food;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FoodMembersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreedySnakePackage.Literals.FOOD_MEMBERS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FoodInitDisplay getFood()
  {
    return food;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFood(FoodInitDisplay newFood, NotificationChain msgs)
  {
    FoodInitDisplay oldFood = food;
    food = newFood;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GreedySnakePackage.FOOD_MEMBERS__FOOD, oldFood, newFood);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFood(FoodInitDisplay newFood)
  {
    if (newFood != food)
    {
      NotificationChain msgs = null;
      if (food != null)
        msgs = ((InternalEObject)food).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GreedySnakePackage.FOOD_MEMBERS__FOOD, null, msgs);
      if (newFood != null)
        msgs = ((InternalEObject)newFood).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GreedySnakePackage.FOOD_MEMBERS__FOOD, null, msgs);
      msgs = basicSetFood(newFood, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.FOOD_MEMBERS__FOOD, newFood, newFood));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreedySnakePackage.FOOD_MEMBERS__FOOD:
        return basicSetFood(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreedySnakePackage.FOOD_MEMBERS__FOOD:
        return getFood();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreedySnakePackage.FOOD_MEMBERS__FOOD:
        setFood((FoodInitDisplay)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.FOOD_MEMBERS__FOOD:
        setFood((FoodInitDisplay)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.FOOD_MEMBERS__FOOD:
        return food != null;
    }
    return super.eIsSet(featureID);
  }

} //FoodMembersImpl
