/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl2.group16.greedySnake.GlobalFieldInitialisation;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;
import org.xtext.example.mydsl2.group16.greedySnake.InitialField;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Global Field Initialisation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getPanelWidth <em>Panel Width</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getPanelHeight <em>Panel Height</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getWidth <em>Width</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getHeight <em>Height</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getLabelWidth <em>Label Width</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getLabelHeight <em>Label Height</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.GlobalFieldInitialisationImpl#getField_initialisation <em>Field initialisation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GlobalFieldInitialisationImpl extends MinimalEObjectImpl.Container implements GlobalFieldInitialisation
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPanelWidth() <em>Panel Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPanelWidth()
   * @generated
   * @ordered
   */
  protected static final int PANEL_WIDTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPanelWidth() <em>Panel Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPanelWidth()
   * @generated
   * @ordered
   */
  protected int panelWidth = PANEL_WIDTH_EDEFAULT;

  /**
   * The default value of the '{@link #getPanelHeight() <em>Panel Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPanelHeight()
   * @generated
   * @ordered
   */
  protected static final int PANEL_HEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPanelHeight() <em>Panel Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPanelHeight()
   * @generated
   * @ordered
   */
  protected int panelHeight = PANEL_HEIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getWidth() <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected static final int WIDTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getWidth() <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected int width = WIDTH_EDEFAULT;

  /**
   * The default value of the '{@link #getHeight() <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHeight()
   * @generated
   * @ordered
   */
  protected static final int HEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHeight() <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHeight()
   * @generated
   * @ordered
   */
  protected int height = HEIGHT_EDEFAULT;

  /**
   * The default value of the '{@link #getLabelWidth() <em>Label Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabelWidth()
   * @generated
   * @ordered
   */
  protected static final int LABEL_WIDTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLabelWidth() <em>Label Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabelWidth()
   * @generated
   * @ordered
   */
  protected int labelWidth = LABEL_WIDTH_EDEFAULT;

  /**
   * The default value of the '{@link #getLabelHeight() <em>Label Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabelHeight()
   * @generated
   * @ordered
   */
  protected static final int LABEL_HEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLabelHeight() <em>Label Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabelHeight()
   * @generated
   * @ordered
   */
  protected int labelHeight = LABEL_HEIGHT_EDEFAULT;

  /**
   * The cached value of the '{@link #getField_initialisation() <em>Field initialisation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getField_initialisation()
   * @generated
   * @ordered
   */
  protected InitialField field_initialisation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GlobalFieldInitialisationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreedySnakePackage.Literals.GLOBAL_FIELD_INITIALISATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPanelWidth()
  {
    return panelWidth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPanelWidth(int newPanelWidth)
  {
    int oldPanelWidth = panelWidth;
    panelWidth = newPanelWidth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_WIDTH, oldPanelWidth, panelWidth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPanelHeight()
  {
    return panelHeight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPanelHeight(int newPanelHeight)
  {
    int oldPanelHeight = panelHeight;
    panelHeight = newPanelHeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_HEIGHT, oldPanelHeight, panelHeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getWidth()
  {
    return width;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWidth(int newWidth)
  {
    int oldWidth = width;
    width = newWidth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__WIDTH, oldWidth, width));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getHeight()
  {
    return height;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHeight(int newHeight)
  {
    int oldHeight = height;
    height = newHeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__HEIGHT, oldHeight, height));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLabelWidth()
  {
    return labelWidth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLabelWidth(int newLabelWidth)
  {
    int oldLabelWidth = labelWidth;
    labelWidth = newLabelWidth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_WIDTH, oldLabelWidth, labelWidth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLabelHeight()
  {
    return labelHeight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLabelHeight(int newLabelHeight)
  {
    int oldLabelHeight = labelHeight;
    labelHeight = newLabelHeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_HEIGHT, oldLabelHeight, labelHeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InitialField getField_initialisation()
  {
    return field_initialisation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetField_initialisation(InitialField newField_initialisation, NotificationChain msgs)
  {
    InitialField oldField_initialisation = field_initialisation;
    field_initialisation = newField_initialisation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION, oldField_initialisation, newField_initialisation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setField_initialisation(InitialField newField_initialisation)
  {
    if (newField_initialisation != field_initialisation)
    {
      NotificationChain msgs = null;
      if (field_initialisation != null)
        msgs = ((InternalEObject)field_initialisation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION, null, msgs);
      if (newField_initialisation != null)
        msgs = ((InternalEObject)newField_initialisation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION, null, msgs);
      msgs = basicSetField_initialisation(newField_initialisation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION, newField_initialisation, newField_initialisation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION:
        return basicSetField_initialisation(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__NAME:
        return getName();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_WIDTH:
        return getPanelWidth();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_HEIGHT:
        return getPanelHeight();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__WIDTH:
        return getWidth();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__HEIGHT:
        return getHeight();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_WIDTH:
        return getLabelWidth();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_HEIGHT:
        return getLabelHeight();
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION:
        return getField_initialisation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__NAME:
        setName((String)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_WIDTH:
        setPanelWidth((Integer)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_HEIGHT:
        setPanelHeight((Integer)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__WIDTH:
        setWidth((Integer)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__HEIGHT:
        setHeight((Integer)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_WIDTH:
        setLabelWidth((Integer)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_HEIGHT:
        setLabelHeight((Integer)newValue);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION:
        setField_initialisation((InitialField)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_WIDTH:
        setPanelWidth(PANEL_WIDTH_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_HEIGHT:
        setPanelHeight(PANEL_HEIGHT_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__WIDTH:
        setWidth(WIDTH_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__HEIGHT:
        setHeight(HEIGHT_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_WIDTH:
        setLabelWidth(LABEL_WIDTH_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_HEIGHT:
        setLabelHeight(LABEL_HEIGHT_EDEFAULT);
        return;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION:
        setField_initialisation((InitialField)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_WIDTH:
        return panelWidth != PANEL_WIDTH_EDEFAULT;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__PANEL_HEIGHT:
        return panelHeight != PANEL_HEIGHT_EDEFAULT;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__WIDTH:
        return width != WIDTH_EDEFAULT;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__HEIGHT:
        return height != HEIGHT_EDEFAULT;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_WIDTH:
        return labelWidth != LABEL_WIDTH_EDEFAULT;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__LABEL_HEIGHT:
        return labelHeight != LABEL_HEIGHT_EDEFAULT;
      case GreedySnakePackage.GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION:
        return field_initialisation != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", panelWidth: ");
    result.append(panelWidth);
    result.append(", panelHeight: ");
    result.append(panelHeight);
    result.append(", width: ");
    result.append(width);
    result.append(", height: ");
    result.append(height);
    result.append(", labelWidth: ");
    result.append(labelWidth);
    result.append(", labelHeight: ");
    result.append(labelHeight);
    result.append(')');
    return result.toString();
  }

} //GlobalFieldInitialisationImpl
