/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl2.group16.greedySnake.AboutSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.Addition;
import org.xtext.example.mydsl2.group16.greedySnake.AllItemVarSpec;
import org.xtext.example.mydsl2.group16.greedySnake.BackSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.BackgroundIcon;
import org.xtext.example.mydsl2.group16.greedySnake.BackgroundTag;
import org.xtext.example.mydsl2.group16.greedySnake.BackgroundTagLocate;
import org.xtext.example.mydsl2.group16.greedySnake.Default;
import org.xtext.example.mydsl2.group16.greedySnake.Expression;
import org.xtext.example.mydsl2.group16.greedySnake.FireInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.FireMembers;
import org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.FoodKind;
import org.xtext.example.mydsl2.group16.greedySnake.FoodMembers;
import org.xtext.example.mydsl2.group16.greedySnake.FoodTime;
import org.xtext.example.mydsl2.group16.greedySnake.GlobalFieldInitialisation;
import org.xtext.example.mydsl2.group16.greedySnake.GlobalMap;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnake;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakeFactory;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;
import org.xtext.example.mydsl2.group16.greedySnake.HelpSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.Icon;
import org.xtext.example.mydsl2.group16.greedySnake.IconTag;
import org.xtext.example.mydsl2.group16.greedySnake.InitialField;
import org.xtext.example.mydsl2.group16.greedySnake.InitialFireSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.InitialFoodSpecificatin;
import org.xtext.example.mydsl2.group16.greedySnake.InitialObstacleSpecificatin;
import org.xtext.example.mydsl2.group16.greedySnake.InitialSnakeSpecificatin;
import org.xtext.example.mydsl2.group16.greedySnake.InitialSpeedSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.IntLiteral;
import org.xtext.example.mydsl2.group16.greedySnake.Maxsize;
import org.xtext.example.mydsl2.group16.greedySnake.Minsize;
import org.xtext.example.mydsl2.group16.greedySnake.Multiplication;
import org.xtext.example.mydsl2.group16.greedySnake.MusicPath;
import org.xtext.example.mydsl2.group16.greedySnake.MusicSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.ObstacleInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.ObstacleMembers;
import org.xtext.example.mydsl2.group16.greedySnake.ObstacleTime;
import org.xtext.example.mydsl2.group16.greedySnake.OptionSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.ParamSpec;
import org.xtext.example.mydsl2.group16.greedySnake.RandomFoodSize;
import org.xtext.example.mydsl2.group16.greedySnake.RealLiteral;
import org.xtext.example.mydsl2.group16.greedySnake.RestartMenu;
import org.xtext.example.mydsl2.group16.greedySnake.SnakeInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.SnakeMembers;
import org.xtext.example.mydsl2.group16.greedySnake.SpeedGroup;
import org.xtext.example.mydsl2.group16.greedySnake.StartFieldDeclaration;
import org.xtext.example.mydsl2.group16.greedySnake.StringVal;
import org.xtext.example.mydsl2.group16.greedySnake.TimeLimited;
import org.xtext.example.mydsl2.group16.greedySnake.VarSpec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GreedySnakePackageImpl extends EPackageImpl implements GreedySnakePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass greedySnakeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass globalMapEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass globalFieldInitialisationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defaultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialSnakeSpecificatinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialFoodSpecificatinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialObstacleSpecificatinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialFireSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialSpeedSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass speedGroupEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fireMembersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass snakeMembersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass foodMembersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass obstacleMembersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fireInitDisplayEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass snakeInitDisplayEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass iconEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass iconTagEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass foodInitDisplayEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass foodKindEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass obstacleInitDisplayEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass randomFoodSizeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass minsizeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass maxsizeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeLimitedEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass obstacleTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass foodTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass varSpecEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass allItemVarSpecEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paramSpecEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass optionSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass restartMenuEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass startFieldDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass aboutSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringValEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass helpSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backgroundIconEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backgroundTagEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass backgroundTagLocateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass musicSpecificationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass musicPathEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass additionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiplicationEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private GreedySnakePackageImpl()
  {
    super(eNS_URI, GreedySnakeFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link GreedySnakePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static GreedySnakePackage init()
  {
    if (isInited) return (GreedySnakePackage)EPackage.Registry.INSTANCE.getEPackage(GreedySnakePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredGreedySnakePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    GreedySnakePackageImpl theGreedySnakePackage = registeredGreedySnakePackage instanceof GreedySnakePackageImpl ? (GreedySnakePackageImpl)registeredGreedySnakePackage : new GreedySnakePackageImpl();

    isInited = true;

    // Create package meta-data objects
    theGreedySnakePackage.createPackageContents();

    // Initialize created meta-data
    theGreedySnakePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theGreedySnakePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(GreedySnakePackage.eNS_URI, theGreedySnakePackage);
    return theGreedySnakePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGreedySnake()
  {
    return greedySnakeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGreedySnake_Name()
  {
    return (EAttribute)greedySnakeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Snakes()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Foods()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Obstacles()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Speed()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Fire()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Time()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Map()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_About()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Help()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Music()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Backgrounds()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Fields()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGreedySnake_Options()
  {
    return (EReference)greedySnakeEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGlobalMap()
  {
    return globalMapEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalMap_Map()
  {
    return (EAttribute)globalMapEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGlobalFieldInitialisation()
  {
    return globalFieldInitialisationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_Name()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_PanelWidth()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_PanelHeight()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_Width()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_Height()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_LabelWidth()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalFieldInitialisation_LabelHeight()
  {
    return (EAttribute)globalFieldInitialisationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGlobalFieldInitialisation_Field_initialisation()
  {
    return (EReference)globalFieldInitialisationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialField()
  {
    return initialFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialField_Name()
  {
    return (EAttribute)initialFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialField_Default()
  {
    return (EReference)initialFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDefault()
  {
    return defaultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefault_Length()
  {
    return (EAttribute)defaultEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefault_Score()
  {
    return (EAttribute)defaultEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefault_Time()
  {
    return (EAttribute)defaultEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefault_Amount()
  {
    return (EAttribute)defaultEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefault_Weapon()
  {
    return (EAttribute)defaultEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialSnakeSpecificatin()
  {
    return initialSnakeSpecificatinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialSnakeSpecificatin_Name()
  {
    return (EAttribute)initialSnakeSpecificatinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialSnakeSpecificatin_Members()
  {
    return (EReference)initialSnakeSpecificatinEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialSnakeSpecificatin_Multiples()
  {
    return (EReference)initialSnakeSpecificatinEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialFoodSpecificatin()
  {
    return initialFoodSpecificatinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialFoodSpecificatin_Name()
  {
    return (EAttribute)initialFoodSpecificatinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialFoodSpecificatin_Members()
  {
    return (EReference)initialFoodSpecificatinEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialFoodSpecificatin_Multiples()
  {
    return (EReference)initialFoodSpecificatinEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialObstacleSpecificatin()
  {
    return initialObstacleSpecificatinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialObstacleSpecificatin_Name()
  {
    return (EAttribute)initialObstacleSpecificatinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialObstacleSpecificatin_Members()
  {
    return (EReference)initialObstacleSpecificatinEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialObstacleSpecificatin_Multiples()
  {
    return (EReference)initialObstacleSpecificatinEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialFireSpecification()
  {
    return initialFireSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInitialFireSpecification_Name()
  {
    return (EAttribute)initialFireSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialFireSpecification_Members()
  {
    return (EReference)initialFireSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialFireSpecification_Multiples()
  {
    return (EReference)initialFireSpecificationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitialSpeedSpecification()
  {
    return initialSpeedSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInitialSpeedSpecification_SpeedGroup()
  {
    return (EReference)initialSpeedSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSpeedGroup()
  {
    return speedGroupEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSpeedGroup_Name()
  {
    return (EAttribute)speedGroupEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSpeedGroup_Value()
  {
    return (EAttribute)speedGroupEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFireMembers()
  {
    return fireMembersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFireMembers_Fire()
  {
    return (EReference)fireMembersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSnakeMembers()
  {
    return snakeMembersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSnakeMembers_Sna()
  {
    return (EReference)snakeMembersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFoodMembers()
  {
    return foodMembersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFoodMembers_Food()
  {
    return (EReference)foodMembersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getObstacleMembers()
  {
    return obstacleMembersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getObstacleMembers_Obstacle()
  {
    return (EReference)obstacleMembersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFireInitDisplay()
  {
    return fireInitDisplayEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFireInitDisplay_FireIcon()
  {
    return (EReference)fireInitDisplayEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFireInitDisplay_Iconsize()
  {
    return (EAttribute)fireInitDisplayEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSnakeInitDisplay()
  {
    return snakeInitDisplayEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSnakeInitDisplay_Head()
  {
    return (EAttribute)snakeInitDisplayEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSnakeInitDisplay_Initial_x()
  {
    return (EAttribute)snakeInitDisplayEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSnakeInitDisplay_Initial_y()
  {
    return (EAttribute)snakeInitDisplayEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSnakeInitDisplay_HeadIcon()
  {
    return (EReference)snakeInitDisplayEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSnakeInitDisplay_Iconsize()
  {
    return (EAttribute)snakeInitDisplayEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSnakeInitDisplay_BodyIcon()
  {
    return (EReference)snakeInitDisplayEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSnakeInitDisplay_DefaultSpeed()
  {
    return (EAttribute)snakeInitDisplayEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSnakeInitDisplay_SnakeTag()
  {
    return (EAttribute)snakeInitDisplayEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIcon()
  {
    return iconEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIcon_IconTag()
  {
    return (EReference)iconEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIconTag()
  {
    return iconTagEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIconTag_Name()
  {
    return (EAttribute)iconTagEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIconTag_Value()
  {
    return (EAttribute)iconTagEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIconTag_Tag()
  {
    return (EAttribute)iconTagEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIconTag_Locate()
  {
    return (EAttribute)iconTagEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFoodInitDisplay()
  {
    return foodInitDisplayEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFoodInitDisplay_FoodIcon()
  {
    return (EReference)foodInitDisplayEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFoodInitDisplay_Iconsize()
  {
    return (EAttribute)foodInitDisplayEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFoodInitDisplay_FoodKind()
  {
    return (EReference)foodInitDisplayEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFoodInitDisplay_Produce()
  {
    return (EReference)foodInitDisplayEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFoodInitDisplay_FoodTag()
  {
    return (EAttribute)foodInitDisplayEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFoodKind()
  {
    return foodKindEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFoodKind_Kind()
  {
    return (EReference)foodKindEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFoodKind_Point()
  {
    return (EReference)foodKindEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getObstacleInitDisplay()
  {
    return obstacleInitDisplayEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getObstacleInitDisplay_ObstacleIcon()
  {
    return (EReference)obstacleInitDisplayEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getObstacleInitDisplay_Iconsize()
  {
    return (EAttribute)obstacleInitDisplayEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getObstacleInitDisplay_ObstacleTag()
  {
    return (EAttribute)obstacleInitDisplayEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRandomFoodSize()
  {
    return randomFoodSizeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRandomFoodSize_Maxsize()
  {
    return (EAttribute)randomFoodSizeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRandomFoodSize_Minsize()
  {
    return (EAttribute)randomFoodSizeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMinsize()
  {
    return minsizeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMinsize_Maxsize()
  {
    return (EAttribute)minsizeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMaxsize()
  {
    return maxsizeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMaxsize_Minsize()
  {
    return (EAttribute)maxsizeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTimeLimited()
  {
    return timeLimitedEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimeLimited_Name()
  {
    return (EAttribute)timeLimitedEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getObstacleTime()
  {
    return obstacleTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getObstacleTime_ObstacleTime()
  {
    return (EAttribute)obstacleTimeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFoodTime()
  {
    return foodTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFoodTime_FoodTime()
  {
    return (EAttribute)foodTimeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVarSpec()
  {
    return varSpecEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVarSpec_Type()
  {
    return (EAttribute)varSpecEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVarSpec_Name()
  {
    return (EAttribute)varSpecEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAllItemVarSpec()
  {
    return allItemVarSpecEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParamSpec()
  {
    return paramSpecEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpression()
  {
    return expressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntLiteral()
  {
    return intLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntLiteral_Val()
  {
    return (EAttribute)intLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealLiteral()
  {
    return realLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRealLiteral_Val()
  {
    return (EAttribute)realLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOptionSpecification()
  {
    return optionSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRestartMenu()
  {
    return restartMenuEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStartFieldDeclaration()
  {
    return startFieldDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStartFieldDeclaration_Field()
  {
    return (EReference)startFieldDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAboutSpecification()
  {
    return aboutSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAboutSpecification_Name()
  {
    return (EAttribute)aboutSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAboutSpecification_AboutTitle()
  {
    return (EAttribute)aboutSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAboutSpecification_AboutInfor()
  {
    return (EAttribute)aboutSpecificationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAboutSpecification_X()
  {
    return (EAttribute)aboutSpecificationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAboutSpecification_Y()
  {
    return (EAttribute)aboutSpecificationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringVal()
  {
    return stringValEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStringVal_Value()
  {
    return (EAttribute)stringValEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHelpSpecification()
  {
    return helpSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getHelpSpecification_Name()
  {
    return (EAttribute)helpSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getHelpSpecification_HelpTitle()
  {
    return (EAttribute)helpSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getHelpSpecification_HelpInfor()
  {
    return (EAttribute)helpSpecificationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getHelpSpecification_X()
  {
    return (EAttribute)helpSpecificationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getHelpSpecification_Y()
  {
    return (EAttribute)helpSpecificationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBackSpecification()
  {
    return backSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBackSpecification_BackgroundIcon()
  {
    return (EReference)backSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackSpecification_BackGroundHeight()
  {
    return (EAttribute)backSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackSpecification_BackGroundWidth()
  {
    return (EAttribute)backSpecificationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBackgroundIcon()
  {
    return backgroundIconEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBackgroundIcon_BackgroundTag()
  {
    return (EReference)backgroundIconEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBackgroundTag()
  {
    return backgroundTagEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackgroundTag_Name()
  {
    return (EAttribute)backgroundTagEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackgroundTag_Value()
  {
    return (EAttribute)backgroundTagEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackgroundTag_BKtag()
  {
    return (EAttribute)backgroundTagEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackgroundTag_Locate()
  {
    return (EAttribute)backgroundTagEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBackgroundTagLocate()
  {
    return backgroundTagLocateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackgroundTagLocate_Name()
  {
    return (EAttribute)backgroundTagLocateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBackgroundTagLocate_Value()
  {
    return (EAttribute)backgroundTagLocateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMusicSpecification()
  {
    return musicSpecificationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMusicSpecification_Buffersize()
  {
    return (EAttribute)musicSpecificationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMusicSpecification_MusicPath()
  {
    return (EReference)musicSpecificationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMusicPath()
  {
    return musicPathEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMusicPath_Name()
  {
    return (EAttribute)musicPathEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMusicPath_Path()
  {
    return (EAttribute)musicPathEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddition()
  {
    return additionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddition_Left()
  {
    return (EReference)additionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddition_Operator()
  {
    return (EAttribute)additionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddition_Right()
  {
    return (EReference)additionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiplication()
  {
    return multiplicationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMultiplication_Left()
  {
    return (EReference)multiplicationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMultiplication_Operator()
  {
    return (EAttribute)multiplicationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMultiplication_Right()
  {
    return (EReference)multiplicationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GreedySnakeFactory getGreedySnakeFactory()
  {
    return (GreedySnakeFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    greedySnakeEClass = createEClass(GREEDY_SNAKE);
    createEAttribute(greedySnakeEClass, GREEDY_SNAKE__NAME);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__SNAKES);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__FOODS);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__OBSTACLES);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__SPEED);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__FIRE);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__TIME);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__MAP);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__ABOUT);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__HELP);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__MUSIC);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__BACKGROUNDS);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__FIELDS);
    createEReference(greedySnakeEClass, GREEDY_SNAKE__OPTIONS);

    globalMapEClass = createEClass(GLOBAL_MAP);
    createEAttribute(globalMapEClass, GLOBAL_MAP__MAP);

    globalFieldInitialisationEClass = createEClass(GLOBAL_FIELD_INITIALISATION);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__NAME);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__PANEL_WIDTH);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__PANEL_HEIGHT);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__WIDTH);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__HEIGHT);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__LABEL_WIDTH);
    createEAttribute(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__LABEL_HEIGHT);
    createEReference(globalFieldInitialisationEClass, GLOBAL_FIELD_INITIALISATION__FIELD_INITIALISATION);

    initialFieldEClass = createEClass(INITIAL_FIELD);
    createEAttribute(initialFieldEClass, INITIAL_FIELD__NAME);
    createEReference(initialFieldEClass, INITIAL_FIELD__DEFAULT);

    defaultEClass = createEClass(DEFAULT);
    createEAttribute(defaultEClass, DEFAULT__LENGTH);
    createEAttribute(defaultEClass, DEFAULT__SCORE);
    createEAttribute(defaultEClass, DEFAULT__TIME);
    createEAttribute(defaultEClass, DEFAULT__AMOUNT);
    createEAttribute(defaultEClass, DEFAULT__WEAPON);

    initialSnakeSpecificatinEClass = createEClass(INITIAL_SNAKE_SPECIFICATIN);
    createEAttribute(initialSnakeSpecificatinEClass, INITIAL_SNAKE_SPECIFICATIN__NAME);
    createEReference(initialSnakeSpecificatinEClass, INITIAL_SNAKE_SPECIFICATIN__MEMBERS);
    createEReference(initialSnakeSpecificatinEClass, INITIAL_SNAKE_SPECIFICATIN__MULTIPLES);

    initialFoodSpecificatinEClass = createEClass(INITIAL_FOOD_SPECIFICATIN);
    createEAttribute(initialFoodSpecificatinEClass, INITIAL_FOOD_SPECIFICATIN__NAME);
    createEReference(initialFoodSpecificatinEClass, INITIAL_FOOD_SPECIFICATIN__MEMBERS);
    createEReference(initialFoodSpecificatinEClass, INITIAL_FOOD_SPECIFICATIN__MULTIPLES);

    initialObstacleSpecificatinEClass = createEClass(INITIAL_OBSTACLE_SPECIFICATIN);
    createEAttribute(initialObstacleSpecificatinEClass, INITIAL_OBSTACLE_SPECIFICATIN__NAME);
    createEReference(initialObstacleSpecificatinEClass, INITIAL_OBSTACLE_SPECIFICATIN__MEMBERS);
    createEReference(initialObstacleSpecificatinEClass, INITIAL_OBSTACLE_SPECIFICATIN__MULTIPLES);

    initialFireSpecificationEClass = createEClass(INITIAL_FIRE_SPECIFICATION);
    createEAttribute(initialFireSpecificationEClass, INITIAL_FIRE_SPECIFICATION__NAME);
    createEReference(initialFireSpecificationEClass, INITIAL_FIRE_SPECIFICATION__MEMBERS);
    createEReference(initialFireSpecificationEClass, INITIAL_FIRE_SPECIFICATION__MULTIPLES);

    initialSpeedSpecificationEClass = createEClass(INITIAL_SPEED_SPECIFICATION);
    createEReference(initialSpeedSpecificationEClass, INITIAL_SPEED_SPECIFICATION__SPEED_GROUP);

    speedGroupEClass = createEClass(SPEED_GROUP);
    createEAttribute(speedGroupEClass, SPEED_GROUP__NAME);
    createEAttribute(speedGroupEClass, SPEED_GROUP__VALUE);

    fireMembersEClass = createEClass(FIRE_MEMBERS);
    createEReference(fireMembersEClass, FIRE_MEMBERS__FIRE);

    snakeMembersEClass = createEClass(SNAKE_MEMBERS);
    createEReference(snakeMembersEClass, SNAKE_MEMBERS__SNA);

    foodMembersEClass = createEClass(FOOD_MEMBERS);
    createEReference(foodMembersEClass, FOOD_MEMBERS__FOOD);

    obstacleMembersEClass = createEClass(OBSTACLE_MEMBERS);
    createEReference(obstacleMembersEClass, OBSTACLE_MEMBERS__OBSTACLE);

    fireInitDisplayEClass = createEClass(FIRE_INIT_DISPLAY);
    createEReference(fireInitDisplayEClass, FIRE_INIT_DISPLAY__FIRE_ICON);
    createEAttribute(fireInitDisplayEClass, FIRE_INIT_DISPLAY__ICONSIZE);

    snakeInitDisplayEClass = createEClass(SNAKE_INIT_DISPLAY);
    createEAttribute(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__HEAD);
    createEAttribute(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__INITIAL_X);
    createEAttribute(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__INITIAL_Y);
    createEReference(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__HEAD_ICON);
    createEAttribute(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__ICONSIZE);
    createEReference(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__BODY_ICON);
    createEAttribute(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__DEFAULT_SPEED);
    createEAttribute(snakeInitDisplayEClass, SNAKE_INIT_DISPLAY__SNAKE_TAG);

    iconEClass = createEClass(ICON);
    createEReference(iconEClass, ICON__ICON_TAG);

    iconTagEClass = createEClass(ICON_TAG);
    createEAttribute(iconTagEClass, ICON_TAG__NAME);
    createEAttribute(iconTagEClass, ICON_TAG__VALUE);
    createEAttribute(iconTagEClass, ICON_TAG__TAG);
    createEAttribute(iconTagEClass, ICON_TAG__LOCATE);

    foodInitDisplayEClass = createEClass(FOOD_INIT_DISPLAY);
    createEReference(foodInitDisplayEClass, FOOD_INIT_DISPLAY__FOOD_ICON);
    createEAttribute(foodInitDisplayEClass, FOOD_INIT_DISPLAY__ICONSIZE);
    createEReference(foodInitDisplayEClass, FOOD_INIT_DISPLAY__FOOD_KIND);
    createEReference(foodInitDisplayEClass, FOOD_INIT_DISPLAY__PRODUCE);
    createEAttribute(foodInitDisplayEClass, FOOD_INIT_DISPLAY__FOOD_TAG);

    foodKindEClass = createEClass(FOOD_KIND);
    createEReference(foodKindEClass, FOOD_KIND__KIND);
    createEReference(foodKindEClass, FOOD_KIND__POINT);

    obstacleInitDisplayEClass = createEClass(OBSTACLE_INIT_DISPLAY);
    createEReference(obstacleInitDisplayEClass, OBSTACLE_INIT_DISPLAY__OBSTACLE_ICON);
    createEAttribute(obstacleInitDisplayEClass, OBSTACLE_INIT_DISPLAY__ICONSIZE);
    createEAttribute(obstacleInitDisplayEClass, OBSTACLE_INIT_DISPLAY__OBSTACLE_TAG);

    randomFoodSizeEClass = createEClass(RANDOM_FOOD_SIZE);
    createEAttribute(randomFoodSizeEClass, RANDOM_FOOD_SIZE__MAXSIZE);
    createEAttribute(randomFoodSizeEClass, RANDOM_FOOD_SIZE__MINSIZE);

    minsizeEClass = createEClass(MINSIZE);
    createEAttribute(minsizeEClass, MINSIZE__MAXSIZE);

    maxsizeEClass = createEClass(MAXSIZE);
    createEAttribute(maxsizeEClass, MAXSIZE__MINSIZE);

    timeLimitedEClass = createEClass(TIME_LIMITED);
    createEAttribute(timeLimitedEClass, TIME_LIMITED__NAME);

    obstacleTimeEClass = createEClass(OBSTACLE_TIME);
    createEAttribute(obstacleTimeEClass, OBSTACLE_TIME__OBSTACLE_TIME);

    foodTimeEClass = createEClass(FOOD_TIME);
    createEAttribute(foodTimeEClass, FOOD_TIME__FOOD_TIME);

    varSpecEClass = createEClass(VAR_SPEC);
    createEAttribute(varSpecEClass, VAR_SPEC__TYPE);
    createEAttribute(varSpecEClass, VAR_SPEC__NAME);

    allItemVarSpecEClass = createEClass(ALL_ITEM_VAR_SPEC);

    paramSpecEClass = createEClass(PARAM_SPEC);

    expressionEClass = createEClass(EXPRESSION);

    intLiteralEClass = createEClass(INT_LITERAL);
    createEAttribute(intLiteralEClass, INT_LITERAL__VAL);

    realLiteralEClass = createEClass(REAL_LITERAL);
    createEAttribute(realLiteralEClass, REAL_LITERAL__VAL);

    optionSpecificationEClass = createEClass(OPTION_SPECIFICATION);

    restartMenuEClass = createEClass(RESTART_MENU);

    startFieldDeclarationEClass = createEClass(START_FIELD_DECLARATION);
    createEReference(startFieldDeclarationEClass, START_FIELD_DECLARATION__FIELD);

    aboutSpecificationEClass = createEClass(ABOUT_SPECIFICATION);
    createEAttribute(aboutSpecificationEClass, ABOUT_SPECIFICATION__NAME);
    createEAttribute(aboutSpecificationEClass, ABOUT_SPECIFICATION__ABOUT_TITLE);
    createEAttribute(aboutSpecificationEClass, ABOUT_SPECIFICATION__ABOUT_INFOR);
    createEAttribute(aboutSpecificationEClass, ABOUT_SPECIFICATION__X);
    createEAttribute(aboutSpecificationEClass, ABOUT_SPECIFICATION__Y);

    stringValEClass = createEClass(STRING_VAL);
    createEAttribute(stringValEClass, STRING_VAL__VALUE);

    helpSpecificationEClass = createEClass(HELP_SPECIFICATION);
    createEAttribute(helpSpecificationEClass, HELP_SPECIFICATION__NAME);
    createEAttribute(helpSpecificationEClass, HELP_SPECIFICATION__HELP_TITLE);
    createEAttribute(helpSpecificationEClass, HELP_SPECIFICATION__HELP_INFOR);
    createEAttribute(helpSpecificationEClass, HELP_SPECIFICATION__X);
    createEAttribute(helpSpecificationEClass, HELP_SPECIFICATION__Y);

    backSpecificationEClass = createEClass(BACK_SPECIFICATION);
    createEReference(backSpecificationEClass, BACK_SPECIFICATION__BACKGROUND_ICON);
    createEAttribute(backSpecificationEClass, BACK_SPECIFICATION__BACK_GROUND_HEIGHT);
    createEAttribute(backSpecificationEClass, BACK_SPECIFICATION__BACK_GROUND_WIDTH);

    backgroundIconEClass = createEClass(BACKGROUND_ICON);
    createEReference(backgroundIconEClass, BACKGROUND_ICON__BACKGROUND_TAG);

    backgroundTagEClass = createEClass(BACKGROUND_TAG);
    createEAttribute(backgroundTagEClass, BACKGROUND_TAG__NAME);
    createEAttribute(backgroundTagEClass, BACKGROUND_TAG__VALUE);
    createEAttribute(backgroundTagEClass, BACKGROUND_TAG__BKTAG);
    createEAttribute(backgroundTagEClass, BACKGROUND_TAG__LOCATE);

    backgroundTagLocateEClass = createEClass(BACKGROUND_TAG_LOCATE);
    createEAttribute(backgroundTagLocateEClass, BACKGROUND_TAG_LOCATE__NAME);
    createEAttribute(backgroundTagLocateEClass, BACKGROUND_TAG_LOCATE__VALUE);

    musicSpecificationEClass = createEClass(MUSIC_SPECIFICATION);
    createEAttribute(musicSpecificationEClass, MUSIC_SPECIFICATION__BUFFERSIZE);
    createEReference(musicSpecificationEClass, MUSIC_SPECIFICATION__MUSIC_PATH);

    musicPathEClass = createEClass(MUSIC_PATH);
    createEAttribute(musicPathEClass, MUSIC_PATH__NAME);
    createEAttribute(musicPathEClass, MUSIC_PATH__PATH);

    additionEClass = createEClass(ADDITION);
    createEReference(additionEClass, ADDITION__LEFT);
    createEAttribute(additionEClass, ADDITION__OPERATOR);
    createEReference(additionEClass, ADDITION__RIGHT);

    multiplicationEClass = createEClass(MULTIPLICATION);
    createEReference(multiplicationEClass, MULTIPLICATION__LEFT);
    createEAttribute(multiplicationEClass, MULTIPLICATION__OPERATOR);
    createEReference(multiplicationEClass, MULTIPLICATION__RIGHT);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    obstacleTimeEClass.getESuperTypes().add(this.getTimeLimited());
    foodTimeEClass.getESuperTypes().add(this.getTimeLimited());
    allItemVarSpecEClass.getESuperTypes().add(this.getVarSpec());
    paramSpecEClass.getESuperTypes().add(this.getVarSpec());
    intLiteralEClass.getESuperTypes().add(this.getExpression());
    realLiteralEClass.getESuperTypes().add(this.getExpression());
    restartMenuEClass.getESuperTypes().add(this.getOptionSpecification());
    startFieldDeclarationEClass.getESuperTypes().add(this.getOptionSpecification());
    additionEClass.getESuperTypes().add(this.getExpression());
    multiplicationEClass.getESuperTypes().add(this.getExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(greedySnakeEClass, GreedySnake.class, "GreedySnake", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGreedySnake_Name(), ecorePackage.getEString(), "name", null, 0, 1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Snakes(), this.getInitialSnakeSpecificatin(), null, "snakes", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Foods(), this.getInitialFoodSpecificatin(), null, "foods", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Obstacles(), this.getInitialObstacleSpecificatin(), null, "obstacles", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Speed(), this.getInitialSpeedSpecification(), null, "speed", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Fire(), this.getInitialFireSpecification(), null, "fire", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Time(), this.getTimeLimited(), null, "time", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Map(), this.getGlobalMap(), null, "Map", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_About(), this.getAboutSpecification(), null, "about", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Help(), this.getHelpSpecification(), null, "Help", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Music(), this.getMusicSpecification(), null, "Music", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Backgrounds(), this.getBackSpecification(), null, "Backgrounds", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Fields(), this.getGlobalFieldInitialisation(), null, "fields", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGreedySnake_Options(), this.getOptionSpecification(), null, "options", null, 0, -1, GreedySnake.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(globalMapEClass, GlobalMap.class, "GlobalMap", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGlobalMap_Map(), ecorePackage.getEString(), "map", null, 0, 1, GlobalMap.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(globalFieldInitialisationEClass, GlobalFieldInitialisation.class, "GlobalFieldInitialisation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGlobalFieldInitialisation_Name(), ecorePackage.getEString(), "name", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalFieldInitialisation_PanelWidth(), ecorePackage.getEInt(), "panelWidth", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalFieldInitialisation_PanelHeight(), ecorePackage.getEInt(), "panelHeight", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalFieldInitialisation_Width(), ecorePackage.getEInt(), "width", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalFieldInitialisation_Height(), ecorePackage.getEInt(), "height", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalFieldInitialisation_LabelWidth(), ecorePackage.getEInt(), "labelWidth", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalFieldInitialisation_LabelHeight(), ecorePackage.getEInt(), "labelHeight", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGlobalFieldInitialisation_Field_initialisation(), this.getInitialField(), null, "field_initialisation", null, 0, 1, GlobalFieldInitialisation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialFieldEClass, InitialField.class, "InitialField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitialField_Name(), ecorePackage.getEString(), "name", null, 0, 1, InitialField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialField_Default(), this.getDefault(), null, "Default", null, 0, 1, InitialField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defaultEClass, Default.class, "Default", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefault_Length(), ecorePackage.getEString(), "length", null, 0, 1, Default.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefault_Score(), ecorePackage.getEString(), "score", null, 0, 1, Default.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefault_Time(), ecorePackage.getEString(), "time", null, 0, 1, Default.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefault_Amount(), ecorePackage.getEString(), "amount", null, 0, 1, Default.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefault_Weapon(), ecorePackage.getEString(), "weapon", null, 0, 1, Default.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialSnakeSpecificatinEClass, InitialSnakeSpecificatin.class, "InitialSnakeSpecificatin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitialSnakeSpecificatin_Name(), ecorePackage.getEString(), "name", null, 0, 1, InitialSnakeSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialSnakeSpecificatin_Members(), this.getSnakeMembers(), null, "members", null, 0, 1, InitialSnakeSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialSnakeSpecificatin_Multiples(), this.getInitialSnakeSpecificatin(), null, "Multiples", null, 0, -1, InitialSnakeSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialFoodSpecificatinEClass, InitialFoodSpecificatin.class, "InitialFoodSpecificatin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitialFoodSpecificatin_Name(), ecorePackage.getEString(), "name", null, 0, 1, InitialFoodSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialFoodSpecificatin_Members(), this.getFoodMembers(), null, "members", null, 0, 1, InitialFoodSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialFoodSpecificatin_Multiples(), this.getInitialFoodSpecificatin(), null, "Multiples", null, 0, -1, InitialFoodSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialObstacleSpecificatinEClass, InitialObstacleSpecificatin.class, "InitialObstacleSpecificatin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitialObstacleSpecificatin_Name(), ecorePackage.getEString(), "name", null, 0, 1, InitialObstacleSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialObstacleSpecificatin_Members(), this.getObstacleMembers(), null, "members", null, 0, 1, InitialObstacleSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialObstacleSpecificatin_Multiples(), this.getInitialObstacleSpecificatin(), null, "Multiples", null, 0, -1, InitialObstacleSpecificatin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialFireSpecificationEClass, InitialFireSpecification.class, "InitialFireSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInitialFireSpecification_Name(), ecorePackage.getEString(), "name", null, 0, 1, InitialFireSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialFireSpecification_Members(), this.getFireMembers(), null, "members", null, 0, 1, InitialFireSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitialFireSpecification_Multiples(), this.getInitialSnakeSpecificatin(), null, "Multiples", null, 0, -1, InitialFireSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initialSpeedSpecificationEClass, InitialSpeedSpecification.class, "InitialSpeedSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInitialSpeedSpecification_SpeedGroup(), this.getSpeedGroup(), null, "speedGroup", null, 0, -1, InitialSpeedSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(speedGroupEClass, SpeedGroup.class, "SpeedGroup", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSpeedGroup_Name(), ecorePackage.getEString(), "name", null, 0, 1, SpeedGroup.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSpeedGroup_Value(), ecorePackage.getEInt(), "value", null, 0, 1, SpeedGroup.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fireMembersEClass, FireMembers.class, "FireMembers", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFireMembers_Fire(), this.getFireInitDisplay(), null, "fire", null, 0, 1, FireMembers.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(snakeMembersEClass, SnakeMembers.class, "SnakeMembers", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSnakeMembers_Sna(), this.getSnakeInitDisplay(), null, "sna", null, 0, 1, SnakeMembers.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(foodMembersEClass, FoodMembers.class, "FoodMembers", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFoodMembers_Food(), this.getFoodInitDisplay(), null, "food", null, 0, 1, FoodMembers.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(obstacleMembersEClass, ObstacleMembers.class, "ObstacleMembers", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getObstacleMembers_Obstacle(), this.getObstacleInitDisplay(), null, "obstacle", null, 0, 1, ObstacleMembers.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fireInitDisplayEClass, FireInitDisplay.class, "FireInitDisplay", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFireInitDisplay_FireIcon(), this.getIconTag(), null, "FireIcon", null, 0, -1, FireInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFireInitDisplay_Iconsize(), ecorePackage.getEString(), "Iconsize", null, 0, 1, FireInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(snakeInitDisplayEClass, SnakeInitDisplay.class, "SnakeInitDisplay", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSnakeInitDisplay_Head(), ecorePackage.getEString(), "head", null, 0, 1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSnakeInitDisplay_Initial_x(), ecorePackage.getEInt(), "initial_x", null, 0, 1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSnakeInitDisplay_Initial_y(), ecorePackage.getEInt(), "initial_y", null, 0, 1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSnakeInitDisplay_HeadIcon(), this.getIconTag(), null, "headIcon", null, 0, -1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSnakeInitDisplay_Iconsize(), ecorePackage.getEString(), "Iconsize", null, 0, 1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSnakeInitDisplay_BodyIcon(), this.getIconTag(), null, "BodyIcon", null, 0, -1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSnakeInitDisplay_DefaultSpeed(), ecorePackage.getEInt(), "defaultSpeed", null, 0, 1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSnakeInitDisplay_SnakeTag(), ecorePackage.getEInt(), "snakeTag", null, 0, 1, SnakeInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(iconEClass, Icon.class, "Icon", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIcon_IconTag(), this.getIconTag(), null, "IconTag", null, 0, -1, Icon.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(iconTagEClass, IconTag.class, "IconTag", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIconTag_Name(), ecorePackage.getEString(), "name", null, 0, 1, IconTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIconTag_Value(), ecorePackage.getEString(), "value", null, 0, 1, IconTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIconTag_Tag(), ecorePackage.getEInt(), "tag", null, 0, 1, IconTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIconTag_Locate(), ecorePackage.getEString(), "Locate", null, 0, 1, IconTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(foodInitDisplayEClass, FoodInitDisplay.class, "FoodInitDisplay", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFoodInitDisplay_FoodIcon(), this.getIconTag(), null, "foodIcon", null, 0, -1, FoodInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFoodInitDisplay_Iconsize(), ecorePackage.getEString(), "Iconsize", null, 0, 1, FoodInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFoodInitDisplay_FoodKind(), this.getFoodKind(), null, "foodKind", null, 0, -1, FoodInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFoodInitDisplay_Produce(), this.getRandomFoodSize(), null, "produce", null, 0, 1, FoodInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFoodInitDisplay_FoodTag(), ecorePackage.getEInt(), "foodTag", null, 0, 1, FoodInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(foodKindEClass, FoodKind.class, "FoodKind", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFoodKind_Kind(), this.getIconTag(), null, "kind", null, 0, 1, FoodKind.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFoodKind_Point(), this.getExpression(), null, "point", null, 0, 1, FoodKind.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(obstacleInitDisplayEClass, ObstacleInitDisplay.class, "ObstacleInitDisplay", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getObstacleInitDisplay_ObstacleIcon(), this.getIconTag(), null, "ObstacleIcon", null, 0, -1, ObstacleInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getObstacleInitDisplay_Iconsize(), ecorePackage.getEString(), "Iconsize", null, 0, 1, ObstacleInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getObstacleInitDisplay_ObstacleTag(), ecorePackage.getEInt(), "ObstacleTag", null, 0, 1, ObstacleInitDisplay.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(randomFoodSizeEClass, RandomFoodSize.class, "RandomFoodSize", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRandomFoodSize_Maxsize(), ecorePackage.getEInt(), "maxsize", null, 0, 1, RandomFoodSize.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRandomFoodSize_Minsize(), ecorePackage.getEInt(), "minsize", null, 0, 1, RandomFoodSize.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(minsizeEClass, Minsize.class, "Minsize", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMinsize_Maxsize(), ecorePackage.getEInt(), "maxsize", null, 0, 1, Minsize.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(maxsizeEClass, Maxsize.class, "Maxsize", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMaxsize_Minsize(), ecorePackage.getEInt(), "minsize", null, 0, 1, Maxsize.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timeLimitedEClass, TimeLimited.class, "TimeLimited", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTimeLimited_Name(), ecorePackage.getEString(), "name", null, 0, 1, TimeLimited.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(obstacleTimeEClass, ObstacleTime.class, "ObstacleTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getObstacleTime_ObstacleTime(), ecorePackage.getEInt(), "ObstacleTime", null, 0, 1, ObstacleTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(foodTimeEClass, FoodTime.class, "FoodTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFoodTime_FoodTime(), ecorePackage.getEInt(), "FoodTime", null, 0, 1, FoodTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(varSpecEClass, VarSpec.class, "VarSpec", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVarSpec_Type(), ecorePackage.getEString(), "type", null, 0, 1, VarSpec.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVarSpec_Name(), ecorePackage.getEString(), "name", null, 0, 1, VarSpec.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(allItemVarSpecEClass, AllItemVarSpec.class, "AllItemVarSpec", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(paramSpecEClass, ParamSpec.class, "ParamSpec", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(expressionEClass, Expression.class, "Expression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(intLiteralEClass, IntLiteral.class, "IntLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntLiteral_Val(), ecorePackage.getEInt(), "val", null, 0, 1, IntLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(realLiteralEClass, RealLiteral.class, "RealLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRealLiteral_Val(), ecorePackage.getEFloat(), "val", null, 0, 1, RealLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(optionSpecificationEClass, OptionSpecification.class, "OptionSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(restartMenuEClass, RestartMenu.class, "RestartMenu", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(startFieldDeclarationEClass, StartFieldDeclaration.class, "StartFieldDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStartFieldDeclaration_Field(), this.getGlobalFieldInitialisation(), null, "field", null, 0, 1, StartFieldDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(aboutSpecificationEClass, AboutSpecification.class, "AboutSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAboutSpecification_Name(), ecorePackage.getEString(), "name", null, 0, 1, AboutSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAboutSpecification_AboutTitle(), ecorePackage.getEString(), "AboutTitle", null, 0, 1, AboutSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAboutSpecification_AboutInfor(), ecorePackage.getEString(), "AboutInfor", null, 0, 1, AboutSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAboutSpecification_X(), ecorePackage.getEInt(), "x", null, 0, 1, AboutSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAboutSpecification_Y(), ecorePackage.getEInt(), "y", null, 0, 1, AboutSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stringValEClass, StringVal.class, "StringVal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringVal_Value(), ecorePackage.getEString(), "value", null, 0, 1, StringVal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(helpSpecificationEClass, HelpSpecification.class, "HelpSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getHelpSpecification_Name(), ecorePackage.getEString(), "name", null, 0, 1, HelpSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHelpSpecification_HelpTitle(), ecorePackage.getEString(), "HelpTitle", null, 0, 1, HelpSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHelpSpecification_HelpInfor(), ecorePackage.getEString(), "HelpInfor", null, 0, 1, HelpSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHelpSpecification_X(), ecorePackage.getEInt(), "x", null, 0, 1, HelpSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getHelpSpecification_Y(), ecorePackage.getEInt(), "y", null, 0, 1, HelpSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backSpecificationEClass, BackSpecification.class, "BackSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBackSpecification_BackgroundIcon(), this.getBackgroundIcon(), null, "BackgroundIcon", null, 0, 1, BackSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackSpecification_BackGroundHeight(), ecorePackage.getEString(), "BackGroundHeight", null, 0, 1, BackSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackSpecification_BackGroundWidth(), ecorePackage.getEString(), "BackGroundWidth", null, 0, 1, BackSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backgroundIconEClass, BackgroundIcon.class, "BackgroundIcon", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBackgroundIcon_BackgroundTag(), this.getBackgroundTag(), null, "BackgroundTag", null, 0, -1, BackgroundIcon.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backgroundTagEClass, BackgroundTag.class, "BackgroundTag", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBackgroundTag_Name(), ecorePackage.getEString(), "name", null, 0, 1, BackgroundTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackgroundTag_Value(), ecorePackage.getEString(), "value", null, 0, 1, BackgroundTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackgroundTag_BKtag(), ecorePackage.getEInt(), "BKtag", null, 0, 1, BackgroundTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackgroundTag_Locate(), ecorePackage.getEString(), "locate", null, 0, 1, BackgroundTag.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(backgroundTagLocateEClass, BackgroundTagLocate.class, "BackgroundTagLocate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBackgroundTagLocate_Name(), ecorePackage.getEString(), "name", null, 0, 1, BackgroundTagLocate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBackgroundTagLocate_Value(), ecorePackage.getEString(), "value", null, 0, 1, BackgroundTagLocate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(musicSpecificationEClass, MusicSpecification.class, "MusicSpecification", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMusicSpecification_Buffersize(), ecorePackage.getEInt(), "buffersize", null, 0, 1, MusicSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMusicSpecification_MusicPath(), this.getMusicPath(), null, "MusicPath", null, 0, -1, MusicSpecification.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(musicPathEClass, MusicPath.class, "MusicPath", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMusicPath_Name(), ecorePackage.getEString(), "name", null, 0, 1, MusicPath.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMusicPath_Path(), ecorePackage.getEString(), "path", null, 0, 1, MusicPath.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(additionEClass, Addition.class, "Addition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAddition_Left(), this.getExpression(), null, "left", null, 0, 1, Addition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAddition_Operator(), ecorePackage.getEString(), "operator", null, 0, -1, Addition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAddition_Right(), this.getExpression(), null, "right", null, 0, -1, Addition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiplicationEClass, Multiplication.class, "Multiplication", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMultiplication_Left(), this.getExpression(), null, "left", null, 0, 1, Multiplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMultiplication_Operator(), ecorePackage.getEString(), "operator", null, 0, -1, Multiplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMultiplication_Right(), this.getExpression(), null, "right", null, 0, -1, Multiplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //GreedySnakePackageImpl
