/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.greedySnake.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;
import org.xtext.example.mydsl2.group16.greedySnake.InitialSpeedSpecification;
import org.xtext.example.mydsl2.group16.greedySnake.SpeedGroup;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initial Speed Specification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.group16.greedySnake.impl.InitialSpeedSpecificationImpl#getSpeedGroup <em>Speed Group</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitialSpeedSpecificationImpl extends MinimalEObjectImpl.Container implements InitialSpeedSpecification
{
  /**
   * The cached value of the '{@link #getSpeedGroup() <em>Speed Group</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeedGroup()
   * @generated
   * @ordered
   */
  protected EList<SpeedGroup> speedGroup;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitialSpeedSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreedySnakePackage.Literals.INITIAL_SPEED_SPECIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SpeedGroup> getSpeedGroup()
  {
    if (speedGroup == null)
    {
      speedGroup = new EObjectContainmentEList<SpeedGroup>(SpeedGroup.class, this, GreedySnakePackage.INITIAL_SPEED_SPECIFICATION__SPEED_GROUP);
    }
    return speedGroup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreedySnakePackage.INITIAL_SPEED_SPECIFICATION__SPEED_GROUP:
        return ((InternalEList<?>)getSpeedGroup()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreedySnakePackage.INITIAL_SPEED_SPECIFICATION__SPEED_GROUP:
        return getSpeedGroup();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreedySnakePackage.INITIAL_SPEED_SPECIFICATION__SPEED_GROUP:
        getSpeedGroup().clear();
        getSpeedGroup().addAll((Collection<? extends SpeedGroup>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.INITIAL_SPEED_SPECIFICATION__SPEED_GROUP:
        getSpeedGroup().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreedySnakePackage.INITIAL_SPEED_SPECIFICATION__SPEED_GROUP:
        return speedGroup != null && !speedGroup.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InitialSpeedSpecificationImpl
