/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl2.group16.greedySnake.FoodInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.GlobalFieldInitialisation;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;
import org.xtext.example.mydsl2.group16.greedySnake.InitialFoodSpecificatin;
import org.xtext.example.mydsl2.group16.greedySnake.InitialObstacleSpecificatin;
import org.xtext.example.mydsl2.group16.greedySnake.InitialSnakeSpecificatin;
import org.xtext.example.mydsl2.group16.greedySnake.ObstacleInitDisplay;
import org.xtext.example.mydsl2.group16.greedySnake.SnakeInitDisplay;
import org.xtext.example.mydsl2.group16.typing.validation.GreedySnakeSystemValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GreedySnakeValidator extends GreedySnakeSystemValidator {
  public static final String INVALID_FIELD_NAME = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_GLOBALFIELD_NAME";
  
  public static final String INVALID_SNAKE_NAME = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_SNAKE_NAME";
  
  public static final String INVALID_FOOD_NAME = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_FOOD_NAME";
  
  public static final String INVALID_OBSTACLE_NAME = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_OBSTACLE_NAME";
  
  public static final String INVALID_WIDTH = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_WIDTH";
  
  public static final String INVALID_SNAKE_TAG = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_SNAKE_TAG";
  
  public static final String INVALID_FOOD_TAG = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_FOOD_TAG";
  
  public static final String INVALID_OBSTACLE_TAG = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_OBSTACLE_TAG";
  
  @Check
  public void checkFieldStartWithLowerCase(final GlobalFieldInitialisation gfi) {
    boolean _isLowerCase = Character.isLowerCase(gfi.getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Name should start with a lower-case character", gfi, GreedySnakePackage.Literals.GLOBAL_FIELD_INITIALISATION__NAME, 
        GreedySnakeValidator.INVALID_FIELD_NAME);
    }
  }
  
  @Check
  public void checkSnakeStartWithLowerCase(final InitialSnakeSpecificatin iss) {
    boolean _isLowerCase = Character.isLowerCase(iss.getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Name should start with a lower-case character", iss, GreedySnakePackage.Literals.INITIAL_SNAKE_SPECIFICATIN__NAME, 
        GreedySnakeValidator.INVALID_SNAKE_NAME);
    }
  }
  
  @Check
  public void checkFoodStartWithLowerCase(final InitialFoodSpecificatin ifs) {
    boolean _isLowerCase = Character.isLowerCase(ifs.getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Name should start with a lower-case character", ifs, GreedySnakePackage.Literals.INITIAL_FOOD_SPECIFICATIN__NAME, 
        GreedySnakeValidator.INVALID_FOOD_NAME);
    }
  }
  
  @Check
  public void checkObsatcleStartWithLowerCase(final InitialObstacleSpecificatin ios) {
    boolean _isLowerCase = Character.isLowerCase(ios.getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Name should start with a lower-case character", ios, GreedySnakePackage.Literals.INITIAL_OBSTACLE_SPECIFICATIN__NAME, 
        GreedySnakeValidator.INVALID_OBSTACLE_NAME);
    }
  }
  
  @Check
  public void checkSnakeTag(final SnakeInitDisplay iss) {
    int _snakeTag = iss.getSnakeTag();
    boolean _tripleNotEquals = (_snakeTag != 1);
    if (_tripleNotEquals) {
      this.warning("Snake Tag must be 1", iss, 
        GreedySnakePackage.Literals.SNAKE_INIT_DISPLAY__SNAKE_TAG, 
        GreedySnakeValidator.INVALID_SNAKE_TAG);
    }
  }
  
  @Check
  public void checkFoodTag(final FoodInitDisplay fid) {
    int _foodTag = fid.getFoodTag();
    boolean _tripleNotEquals = (_foodTag != 2);
    if (_tripleNotEquals) {
      this.warning("Food Tag must be 2", fid, 
        GreedySnakePackage.Literals.FOOD_INIT_DISPLAY__FOOD_TAG, 
        GreedySnakeValidator.INVALID_FOOD_TAG);
    }
  }
  
  @Check
  public void checkObstacleTag(final ObstacleInitDisplay oid) {
    int _obstacleTag = oid.getObstacleTag();
    boolean _tripleNotEquals = (_obstacleTag != 3);
    if (_tripleNotEquals) {
      this.warning("Obstacle Tag must be 3", oid, 
        GreedySnakePackage.Literals.OBSTACLE_INIT_DISPLAY__OBSTACLE_TAG, 
        GreedySnakeValidator.INVALID_OBSTACLE_TAG);
    }
  }
}
