/**
 * generated by Xtext 2.25.0.M1
 */
package org.xtext.example.mydsl2.group16.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl2.group16.greedySnake.GlobalFieldInitialisation;
import org.xtext.example.mydsl2.group16.greedySnake.GreedySnakePackage;
import org.xtext.example.mydsl2.group16.typing.validation.GreedySnakeSystemValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GreedySnakeValidator extends GreedySnakeSystemValidator {
  public static final String INVALID_NAME = "org.xtext.example.mydsl2.group16.greedySnake.INVALID_GLOBALFIELD_NAME";
  
  @Check
  public void checkVariableStartWithLowerCase(final GlobalFieldInitialisation gfi) {
    boolean _isLowerCase = Character.isLowerCase(gfi.getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Name should start with a lower-case character", gfi, GreedySnakePackage.Literals.GLOBAL_FIELD_INITIALISATION__NAME, 
        GreedySnakeValidator.INVALID_NAME);
    }
  }
}
